### ISSUE TITLE
Obsidian Mobile compatibility

### ISSUE THREAD

**Issue by symph0nic** [jamiebrynes7/obsidian-todoist-plugin#100]
**Is your feature request related to a problem? Please describe.**
Not really - Obsidian on the ipad is going to be a major workflow for me so I want to keep the functionality the same as on the desktop.

**Describe the solution you'd like**
Full compatibility with the mobile iteration of Obsidian

**Describe alternatives you've considered**

**Additional context**
With the current version (0.0.12) the plugin installs, but errors when you try to turn it on in the settings.

**Comment by jamiebrynes7** [comment]
Hey @symph0nic, while I'm interested in figuring out why the plugin currently doesn't work, I'll need to wait for wider availability for the mobile apps.

**Comment by Finnvoor** [comment]
In case you're still interested, the reason the plugin doesn't work on mobile is due to it requiring the "electron" and "process" modules:

https://github.com/jamiebrynes7/obsidian-todoist-plugin/blob/be86a3b6035f0693f0eecbb81032e318c0f2f6aa/src/utils.ts#L3

https://github.com/jamiebrynes7/obsidian-todoist-plugin/blob/be86a3b6035f0693f0eecbb81032e318c0f2f6aa/src/utils.ts#L51-L59

https://github.com/jamiebrynes7/obsidian-todoist-plugin/blob/be86a3b6035f0693f0eecbb81032e318c0f2f6aa/src/contextMenu.ts#L46-L48

I was able to build a version that works on mobile by getting rid of the context menus entirely and hardcoding the token path as I do not need support for Windows.

This line was also giving me some issues, I had to remove the `() => true`

https://github.com/jamiebrynes7/obsidian-todoist-plugin/blob/be86a3b6035f0693f0eecbb81032e318c0f2f6aa/src/index.ts#L98

**Comment by ekmekjian** [comment]
Is there any update as to whether this will happen? This would make task management in obsidian perfect.

**Comment by jamiebrynes7** [comment]
The plugin should be compatible with mobile as of [v1.8.0](https://github.com/jamiebrynes7/obsidian-todoist-plugin/releases/tag/1.8.0)!
