### ISSUE TITLE
Make tasks searchable in Obsidian?

### ISSUE THREAD

**Issue by pm64** [jamiebrynes7/obsidian-todoist-plugin#217]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to search in two different places for text that may appear inside or outside of a task description.

**Describe the solution you'd like**
Make tasks materialized by this plugin searchable in Obsidian.

**Describe alternatives you've considered**
There are no automated alternatives, to my knowledge.

**Additional context**
I'm not sure if this is possible, because I'm not entirely sure what the scope of Obsidian's search feature is. In the worst case, maybe task descriptions could be included in some hidden HTML?

**Comment by jamiebrynes7** [comment]
> I'm not sure if this is possible, because I'm not entirely sure what the scope of Obsidian's search feature is.

This is basically the core issue. From what I can tell, the search operates on the underlying document rather than what is rendered in the view, so searching (both with Ctrl+F in the document and via the Search tab) cannot work with this plugin.

Unless the Obsidian team expose an interface to searching in their API, this won't be possible.
