### ISSUE TITLE
Load Sub-Tasks of a Particular Task

### ISSUE THREAD

**Issue by max-dfinity** [jamiebrynes7/obsidian-todoist-plugin#218]
**Is your feature request related to a problem? Please describe.**
I want a way to load all the subtasks of a particuar task.  An example is when I'm working on a JIRA ticket.  I make a top-level ticket in todoist with a link to the ticket, and then I add sub-tasks so I can keep track of my Next Actions as I'm working (GTD).

Currently, there is no way that I know of to query for the subtasks of a particular task.  
**Describe the solution you'd like**
I would like a way through the API to load subtasks of a particular task.  Having something else other than just 'filter', that lets you specify a task to load subtasks of would be really useful in a lot of situations.

**Describe alternatives you've considered**
I have tried to be very clever with my filters, but I cannot figure out the magic.  If there is such a magic, I don't need this feature.

**Additional context**

**Comment by jamiebrynes7** [comment]
Hey @max-dfinity, this isn't something that I'm looking to support right now

**Comment by jottr** [comment]
Hi jamie, 
thank you for this awesome plugin. 
It would be extremely useful if one could easily render sub-tasks. Why are you not interested in supporting this feature?
Would you be willing to accept PRs that implement this?

**Comment by jamiebrynes7** [comment]
The core reason is that its not necessarily straightforward to implement this. We can fetch individual tasks by task ID, but subtasks are not included in the response. We could fetch _all_ tasks and filter them, but this feels like an abuse of the API. 

I'd be more willing to look at this if/when this migrates onto the sync API, since the expectation is that we keep an entire copy of the application state. I've not done this migration (yet) because it would force me to re-implement all the Todoist filters and I'm not sure if that's a level of complexity I want to commit to.

**Comment by jottr** [comment]
>  We can fetch individual tasks by task ID, but subtasks are not included in the response. 
Yeah, I noticed this too while looking at the API doc.
It's a peculiar implementation detail. 

As an intermediate step, one could use the Sync API to just pull in the parent-child relationships and stay on the REST API for the filtering tasks.

**Comment by jamiebrynes7** [comment]
While that could work, if I do start using the Sync API it would to start porting existing functionality across first, before building on top of what already exists.
