### ISSUE TITLE
"Show: labels" doesn't work

### ISSUE THREAD

**Issue by derekantrican** [jamiebrynes7/obsidian-todoist-plugin#318]
**Describe the bug**
Putting "Show: labels" in a query doesn't work

**To Reproduce**
1. Ensure the setting "Enable labels" is turned off (especially since this will be deprecated anyway)
2. Insert the following YAML query (note: filter is not important - as long as the shown tasks have labels):

```todoist
name: "My Tasks"
filter: "today | overdue"
show:  
    - labels
```
_Note: the above query was created referencing [the documentation](https://jamiebrynes7.github.io/obsidian-todoist-plugin/docs/query-blocks#show)_

3. Tasks are shown without labels

**Expected behavior**
Tasks should respect the "show" part of the query, but instead seem to be only respecting the plugin settings (which will be deprecated soon)

**Screenshots**
![Obsidian_SxXnxLIVYk](https://github.com/jamiebrynes7/obsidian-todoist-plugin/assets/1558019/260f2309-5af7-4247-b473-72b03b89e517)

**Desktop (please complete the following information):**
 - Plugin Version 1.13.0
 - Obsidian Version 1.15.12

**Comment by jamiebrynes7** [comment]
This is actually the intended behaviour (if slightly unintuitive). The settings option is "global" and will take precedence over the local setting.

If you are using the `show` option, I recommend leaving the all the global options turned on since this:

- gives you fine-grained control
- matches the behaviour once the options are removed

In any case, the global options are going to be removed in the next release, so this will cease to be a problem shortly

**Comment by derekantrican** [comment]
Ok, then I guess the problem description should be rephrased: it does not appear to be currently possible with this plugin to show lists of todoist tasks where some show labels and some don't. That is to say: the setting "Enable labels" in the plugin settings is the only control for whether labels are shown and changing the query "Show: labels" (adding it or removing it) doesn't do anything

**Comment by jamiebrynes7** [comment]
To be clear, the global settings are going to be removed in the next release - so this behaviour will go away. In the interim, I will not be changing the interaction of the global & query-specific configuration.
